from django.urls import path

from .views import (
    AdminLoginView,
    AlumniCreateView,
    AlumniDeleteView,
    AlumniListView,
    AlumniUpdateView,
    AnnouncementCreateView,
    AnnouncementDeleteView,
    AnnouncementListView,
    AnnouncementUpdateView,
    DepartmentCreateView,
    DepartmentDeleteView,
    DepartmentListView,
    EventCreateView,
    EventDeleteView,
    EventListView,
    EventUpdateView,
    InstructorCreateView,
    InstructorDeleteView,
    InstructorListView,
    NewsCreateView,
    NewsDeleteView,
    NewsListView,
    ProgramCreateView,
    ProgramDeleteView,
    ProgramListView,
    DashboardRedirectView,
    DepartmentAdminDashboardView,
    DepartmentAdminCreateView,
    DepartmentAdminListView,
    DepartmentAdminToggleStatusView,
    DepartmentAdminUpdateView,
    DepartmentUpdateView,
    InstructorUpdateView,
    NewsUpdateView,
    ProgramUpdateView,
    SchoolInfoUpdateView,
    SuperAdminDashboardView,
    admin_logout,
)

app_name = "accounts"

urlpatterns = [
    # Authentication and dashboard entry points
    path("login/", AdminLoginView.as_view(), name="login"),
    path("logout/", admin_logout, name="logout"),
    path("dashboard/", DashboardRedirectView.as_view(), name="dashboard"),
    path("dashboard/super-admin/", SuperAdminDashboardView.as_view(), name="super_admin_dashboard"),
    path("dashboard/department/", DepartmentAdminDashboardView.as_view(), name="department_admin_dashboard"),

    # Super admin management
    path("dashboard/super-admin/school-info/", SchoolInfoUpdateView.as_view(), name="school_info_update"),
    path("dashboard/super-admin/departments/", DepartmentListView.as_view(), name="department_list"),
    path("dashboard/super-admin/departments/add/", DepartmentCreateView.as_view(), name="department_create"),
    path("dashboard/super-admin/departments/<int:pk>/edit/", DepartmentUpdateView.as_view(), name="department_update"),
    path("dashboard/super-admin/departments/<int:pk>/delete/", DepartmentDeleteView.as_view(), name="department_delete"),
    path("dashboard/super-admin/department-admins/", DepartmentAdminListView.as_view(), name="department_admin_list"),
    path("dashboard/super-admin/department-admins/add/", DepartmentAdminCreateView.as_view(), name="department_admin_create"),
    path("dashboard/super-admin/department-admins/<int:pk>/edit/", DepartmentAdminUpdateView.as_view(), name="department_admin_update"),
    path("dashboard/super-admin/department-admins/<int:pk>/toggle-status/", DepartmentAdminToggleStatusView.as_view(), name="department_admin_toggle_status"),

    # Shared content and record management
    path("programs/", ProgramListView.as_view(), name="program_list"),
    path("programs/add/", ProgramCreateView.as_view(), name="program_create"),
    path("programs/<int:pk>/edit/", ProgramUpdateView.as_view(), name="program_update"),
    path("programs/<int:pk>/delete/", ProgramDeleteView.as_view(), name="program_delete"),
    path("announcements/", AnnouncementListView.as_view(), name="announcement_list"),
    path("announcements/add/", AnnouncementCreateView.as_view(), name="announcement_create"),
    path("announcements/<int:pk>/edit/", AnnouncementUpdateView.as_view(), name="announcement_update"),
    path("announcements/<int:pk>/delete/", AnnouncementDeleteView.as_view(), name="announcement_delete"),
    path("news/", NewsListView.as_view(), name="news_list"),
    path("news/add/", NewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/edit/", NewsUpdateView.as_view(), name="news_update"),
    path("news/<int:pk>/delete/", NewsDeleteView.as_view(), name="news_delete"),
    path("events/", EventListView.as_view(), name="event_list"),
    path("events/add/", EventCreateView.as_view(), name="event_create"),
    path("events/<int:pk>/edit/", EventUpdateView.as_view(), name="event_update"),
    path("events/<int:pk>/delete/", EventDeleteView.as_view(), name="event_delete"),
    path("alumni/", AlumniListView.as_view(), name="alumni_list"),
    path("alumni/add/", AlumniCreateView.as_view(), name="alumni_create"),
    path("alumni/<int:pk>/edit/", AlumniUpdateView.as_view(), name="alumni_update"),
    path("alumni/<int:pk>/delete/", AlumniDeleteView.as_view(), name="alumni_delete"),
    path("instructors/", InstructorListView.as_view(), name="instructor_list"),
    path("instructors/add/", InstructorCreateView.as_view(), name="instructor_create"),
    path("instructors/<int:pk>/edit/", InstructorUpdateView.as_view(), name="instructor_update"),
    path("instructors/<int:pk>/delete/", InstructorDeleteView.as_view(), name="instructor_delete"),
]
