# Generated by Django 5.2.12 on 2026-04-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
