# Generated by Django 5.2.12 on 2026-04-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_leadership_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
