# Generated by Django 5.2.12 on 2026-04-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_make_updates_department_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="departments.department",
            ),
        ),
    ]
